name = "ReactiveECS"
uuid = "98e33af6-2ee5-5afd-9e75-cbc738b765c9"
repo = "https://github.com/Gesee-y/ReactiveECS.jl.git"
version = "1.0.0"

[deps]
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"

[compat]
julia = "1.10.3"
StructArrays = "0.7.1"
OrderedCollections = "1.8.1"
