name = "ReactiveECS"
uuid = "98e33af6-2ee5-5afd-9e75-cbc738b765c9"
repo = "https://github.com/Gesee-y/ReactiveECS.jl.git"
version = "1.0.1"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"

[compat]
OrderedCollections = "1.8.1"
StructArrays = "0.7.1"
julia = "1.10.1"
